SET FOREIGN_KEY_CHECKS=0;

-- Data for faculties
TRUNCATE TABLE `faculties`;
INSERT INTO `faculties` (`id`, `name`, `code`, `created_at`, `updated_at`, `description`, `website`) VALUES ('1', 'Fakultas Komputer', 'FAKOM', '2026-07-16 09:18:45', '2026-07-16 09:18:45', NULL, NULL);

-- Data for program_studis
TRUNCATE TABLE `program_studis`;
INSERT INTO `program_studis` (`id`, `name`, `code`, `faculty_id`, `created_at`, `updated_at`, `submission_start`, `submission_end`, `description`, `max_batches`, `attempts_per_batch`) VALUES ('1', 'Teknik Perangkat Lunak', 'TPL', '1', '2026-07-16 09:18:45', '2026-07-16 09:18:45', NULL, NULL, NULL, '2', '3');

-- Data for users
TRUNCATE TABLE `users`;
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('1', 'Administrator', 'admin@ta.test', NULL, '$2y$12$C3k2V9rVURVGZ8OCaWh6Iu8XF52C86QXWUcH0I8Z0u2M05zQ6leAe', NULL, NULL, NULL, NULL, '1', NULL, NULL, '2026-07-16 09:18:45', '2026-07-16 09:18:45', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('2', 'Kaharuddin, S.Kom., M.Kom', 'kaharuddin@ta.test', NULL, '$2y$12$3sWq/SrQPq31Fd1kwuYVEes73TDPvZ2DJWZXlkZXyPtgpbvBt3.Oi', 'D001', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:46', '2026-07-16 09:18:46', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('3', 'Ilwan Syafrinal, S.Kom., M.Kom', 'ilwan@ta.test', NULL, '$2y$12$dmSvejOd2hJ6aXEFZ776zuWcbpPqbYeu3lb3OtFktMP3I.I9LGTvy', 'D002', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:46', '2026-07-16 09:18:46', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('4', 'Eka Lia Febrianti, S.Kom., M.Kom.', 'ekalia@ta.test', NULL, '$2y$12$MPNPQprcjcH4med/gSFjm.IXFZsxw1a5Av5BXp9PEHFO6KmgRs2qy', 'D003', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:46', '2026-07-16 09:18:46', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('5', 'Masparudin, S.Kom., M.Kom.', 'masparudin@ta.test', NULL, '$2y$12$M8LQLoFe0.RVA3Nkt7QVOe/5Fg2.o3aIY2JQMGJGUHYO80c7i49CS', 'D004', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:46', '2026-07-16 09:18:46', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('6', 'Alex Ferguson', 'alexferguson@ta.test', NULL, '$2y$12$cxER2IvGEjmDCGyigtH89uTfDR67AF4qxVTHuDuswDhkSy1of0MWa', '2022133011', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('7', 'Calvin Whenjaya', 'calvinwhenjaya@ta.test', NULL, '$2y$12$H2yLsZfcPCeli347Fkhaxu2yowV4Z4ZyQZXippXfNvUcW0Auv38Z6', '2022133001', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('8', 'Duandi', 'duandi@ta.test', NULL, '$2y$12$39a0x.9hD/9AJGlFeifk/OI9ZwBKeNsFnhKoQgSs8pXU08RmuUI16', '2022133012', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('9', 'Dustin Walter Lim', 'dustinwalterlim@ta.test', NULL, '$2y$12$YHUcTD3jCjQ3RCDF0eAguuahGfeIpuhYkZV1nk8F0P20Ws.ma/Rg6', '2022133002', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('10', 'Edison', 'edison@ta.test', NULL, '$2y$12$FJIADE0B442EyGH4BWnvn.lolsQCjD5S2pv3YjEfUToIea.xCdxfm', '2022133007', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('11', 'Fariwati', 'fariwati@ta.test', NULL, '$2y$12$7P1r6qsIHDBIQkGLNxPDHOd5k5IYxOHj1V7YLmFXuec278RX7QiPK', '2022133014', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('12', 'Hadi Susanto', 'hadisusanto@ta.test', NULL, '$2y$12$Orx0MO9ugj2GoyFYl7ybjef925/bmHs1NOHyNYxzGUfTWwffVMHlu', '2022133003', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('13', 'Herman', 'herman@ta.test', NULL, '$2y$12$vZpBNg743J/qDajALqqLy.myyWV96EjMWoH16Lega6CBROE.PtW6W', '2022133006', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('14', 'Khenjy Johnelson', 'khenjyjohnelson@ta.test', NULL, '$2y$12$KkngIDHd0BJKfYfEI1ks9uGI9SX/Bf9Oo86HeG9ipwE85RzxBw7rC', '2022133005', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('15', 'Lily', 'lily@ta.test', NULL, '$2y$12$p11Cj4U7zZUG4ef9xGW8au7plSu/4ZqDhflZw5IsjfcjDDZ8F4qpS', '2022133010', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('16', 'Richard', 'richard@ta.test', NULL, '$2y$12$mXPxa2qfFN0GdgJZW2ynuOxnBP00R6TuwJ43hT68T7mKDI2IDAJtC', '2022133013', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('17', 'Steven Tang', 'steventang@ta.test', NULL, '$2y$12$SwDvM7Na.S.YZHa/waRJAOkBMXkyuVVR0O5dMFB8v62S.1NXIfhCC', '2022133008', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('18', 'Venessya Calista', 'venessyacalista@ta.test', NULL, '$2y$12$zaSZc5oHB18lin.XzCS30eFGUxA6BgrtDHqt7G/sF/1ju.QrSfKpC', '2022133017', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:50', '2026-07-16 09:18:50', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('19', 'Vito Timothi', 'vitotimothi@ta.test', NULL, '$2y$12$CcwjJHP6o7jUwG8mfKf6QuEzbwK3m24yD/NPa5oYvmpPJ8JBqv.j.', '2022133018', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:50', '2026-07-16 09:18:50', NULL, NULL, '0');
INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `nim_nip`, `phone`, `address`, `profile_photo`, `is_active`, `program_studi_id`, `remember_token`, `created_at`, `updated_at`, `deleted_at`, `angkatan`, `can_exceed_submission_limit`) VALUES ('20', 'Vivie Triyanti', 'vivietriyanti@ta.test', NULL, '$2y$12$ZGNwFfIB3MB5kkF7I3D3Zeu5aRcB7A/3BJsE1NaO/QFg7NjkQ3QhS', '2022133004', NULL, NULL, NULL, '1', '1', NULL, '2026-07-16 09:18:50', '2026-07-16 09:18:50', NULL, NULL, '0');

-- Data for roles
TRUNCATE TABLE `roles`;
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('1', 'admin', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('2', 'kaprodi', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('3', 'dosen', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `roles` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('4', 'mahasiswa', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');

-- Data for permissions
TRUNCATE TABLE `permissions`;
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('1', 'view menu: mahasiswa', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('2', 'view menu: dosen', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('3', 'view menu: kaprodi', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('4', 'view menu: admin', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('5', 'view menu: reports', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('6', 'view users', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('7', 'create users', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('8', 'edit users', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('9', 'delete users', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('10', 'view submissions', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('11', 'create submissions', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('12', 'edit submissions', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('13', 'delete submissions', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('14', 'approve submissions', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('15', 'reject submissions', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('16', 'assign lecturers', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('17', 'view assessments', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('18', 'create assessments', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('19', 'edit assessments', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('20', 'delete assessments', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('21', 'view activity logs', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('22', 'view reports', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('23', 'manage settings', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('24', 'manage rubrics', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('25', 'manage faculties', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('26', 'manage program-studis', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('27', 'manage configuration', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');
INSERT INTO `permissions` (`id`, `name`, `guard_name`, `created_at`, `updated_at`) VALUES ('28', 'manage rbac', 'web', '2026-07-16 09:18:45', '2026-07-16 09:18:45');

-- Data for model_has_roles
TRUNCATE TABLE `model_has_roles`;
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('1', 'App\\Models\\User', '1');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('2', 'App\\Models\\User', '2');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('3', 'App\\Models\\User', '2');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('3', 'App\\Models\\User', '3');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('3', 'App\\Models\\User', '4');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('3', 'App\\Models\\User', '5');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '6');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '7');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '8');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '9');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '10');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '11');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '12');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '13');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '14');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '15');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '16');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '17');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '18');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '19');
INSERT INTO `model_has_roles` (`role_id`, `model_type`, `model_id`) VALUES ('4', 'App\\Models\\User', '20');

-- Data for role_has_permissions
TRUNCATE TABLE `role_has_permissions`;
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('1', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('2', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('3', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('4', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('5', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('6', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('7', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('8', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('9', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('10', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('11', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('12', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('13', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('14', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('15', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('16', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('17', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('18', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('19', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('20', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('21', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('22', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('23', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('24', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('25', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('26', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('27', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('28', '1');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('2', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('3', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('5', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('6', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('10', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('14', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('15', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('16', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('17', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('21', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('22', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('23', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('24', '2');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('2', '3');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('10', '3');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('12', '3');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('14', '3');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('17', '3');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('18', '3');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('19', '3');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('1', '4');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('10', '4');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('11', '4');
INSERT INTO `role_has_permissions` (`permission_id`, `role_id`) VALUES ('12', '4');

-- Data for thesis_submissions
TRUNCATE TABLE `thesis_submissions`;
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('1', '6', '3', 'Perancangan Sistem Monitoring Maintenance Sarana dan Prasarana di Universitas Universal Berbasis Web', 'Abstrak untuk Perancangan Sistem Monitoring Maintenance Sarana dan Prasarana di Universitas Universal Berbasis Web', 'Teknik Perangkat Lunak', 'approved', '2026-07-12 09:18:47', NULL, NULL, NULL, '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('2', '7', '5', 'Perancangan Aplikasi Pendeteksi Makanan Cemilan Vegetarian Yang Tidak Sehat Berbasis Image Recognition Untuk Membantu Pola Hidup Sehat', 'Abstrak untuk Perancangan Aplikasi Pendeteksi Makanan Cemilan Vegetarian Yang Tidak Sehat Berbasis Image Recognition Untuk Membantu Pola Hidup Sehat', 'Teknik Perangkat Lunak', 'approved', '2026-06-28 09:18:47', NULL, NULL, NULL, '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL, NULL, '4', '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('3', '8', '3', 'Rancang Bangun Sistem Pengajuan Proposal Tugas Akhir Berbasis Web Menggunakan Metode Agile SCRUM', 'Abstrak untuk Rancang Bangun Sistem Pengajuan Proposal Tugas Akhir Berbasis Web Menggunakan Metode Agile SCRUM', 'Teknik Perangkat Lunak', 'approved', '2026-07-14 09:18:47', NULL, NULL, NULL, '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('4', '9', '2', 'Perancangan Game Eksplorasi Interaktif Ruang Galeri Seni Universitas Universal Sebagai Media Promosi', 'Abstrak untuk Perancangan Game Eksplorasi Interaktif Ruang Galeri Seni Universitas Universal Sebagai Media Promosi', 'Teknik Perangkat Lunak', 'approved', '2026-07-05 09:18:47', NULL, NULL, NULL, '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('5', '10', '4', 'Rancang Bangun Website Penilaian Konsumsi Gula pada Minuman dengan Sistem Grade dan Rekomendasi', 'Abstrak untuk Rancang Bangun Website Penilaian Konsumsi Gula pada Minuman dengan Sistem Grade dan Rekomendasi', 'Teknik Perangkat Lunak', 'approved', '2026-07-13 09:18:48', NULL, NULL, NULL, '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('6', '11', '2', 'Perancangan Game Edukatif  Sebagai Media Pembelajaran Interaktif Dalam Pengenalan Tabel Unsur Periodik Terhadap Siswa SMA', 'Abstrak untuk Perancangan Game Edukatif  Sebagai Media Pembelajaran Interaktif Dalam Pengenalan Tabel Unsur Periodik Terhadap Siswa SMA', 'Teknik Perangkat Lunak', 'approved', '2026-06-23 09:18:48', NULL, NULL, NULL, '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('7', '12', '4', 'Rancang Bangun Aplikasi Tour Guide Pintar Berbasis Lokasi dengan Rekomendasi Tempat Otomatis di Batam.', 'Abstrak untuk Rancang Bangun Aplikasi Tour Guide Pintar Berbasis Lokasi dengan Rekomendasi Tempat Otomatis di Batam.', 'Teknik Perangkat Lunak', 'approved', '2026-07-08 09:18:48', NULL, NULL, NULL, '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('8', '13', '4', 'Perancangan Sistem Informasi Manajemen Servis Berbasis Web Untuk Meningkatkan Efisiensi Pelacakan Pekerjaan Pada CV ITC', 'Abstrak untuk Perancangan Sistem Informasi Manajemen Servis Berbasis Web Untuk Meningkatkan Efisiensi Pelacakan Pekerjaan Pada CV ITC', 'Teknik Perangkat Lunak', 'approved', '2026-07-02 09:18:48', NULL, NULL, NULL, '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('9', '14', '5', 'Perancangan Penjadwalan Sistem Informasi Akademik di Universitas Universal', 'Abstrak untuk Perancangan Penjadwalan Sistem Informasi Akademik di Universitas Universal', 'Teknik Perangkat Lunak', 'approved', '2026-06-18 09:18:49', NULL, NULL, NULL, '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL, NULL, '4', '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('10', '15', '5', 'Aplikasi Mobile “E-Disiplin” Sebagai Media Pencatatan Dan Pemantauan Poin Pelanggaran Tata Tertib Mahasiswa Di Universitas Universal', 'Abstrak untuk Aplikasi Mobile “E-Disiplin” Sebagai Media Pencatatan Dan Pemantauan Poin Pelanggaran Tata Tertib Mahasiswa Di Universitas Universal', 'Teknik Perangkat Lunak', 'approved', '2026-07-14 09:18:49', NULL, NULL, NULL, '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL, NULL, '4', '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('11', '16', '3', 'Perancangan Sistem Inventory Stok Barang Berbasis Database Website untuk Optimalisasi Manajemen Persediaan Stok', 'Abstrak untuk Perancangan Sistem Inventory Stok Barang Berbasis Database Website untuk Optimalisasi Manajemen Persediaan Stok', 'Teknik Perangkat Lunak', 'approved', '2026-06-26 09:18:49', NULL, NULL, NULL, '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('12', '17', '4', 'Rancang Bangun Website StudyStrip Sebagai Media Pembelajaran Interaktif Berbasis Komik Digital', 'Abstrak untuk Rancang Bangun Website StudyStrip Sebagai Media Pembelajaran Interaktif Berbasis Komik Digital', 'Teknik Perangkat Lunak', 'approved', '2026-06-24 09:18:49', NULL, NULL, NULL, '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('13', '18', '2', 'Perancangan Game Visual Novel Interaktif di Platform Roblox sebagai Media Edukasi Pencegahan Bullying dan Kekerasan Verbal', 'Abstrak untuk Perancangan Game Visual Novel Interaktif di Platform Roblox sebagai Media Edukasi Pencegahan Bullying dan Kekerasan Verbal', 'Teknik Perangkat Lunak', 'approved', '2026-07-01 09:18:50', NULL, NULL, NULL, '2026-07-16 09:18:50', '2026-07-16 09:18:50', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('14', '19', '3', 'Pengembangan Sistem Informasi Berbasis Website Untuk Manajemen Dan Publikasi Event Di Uvers', 'Abstrak untuk Pengembangan Sistem Informasi Berbasis Website Untuk Manajemen Dan Publikasi Event Di Uvers', 'Teknik Perangkat Lunak', 'approved', '2026-07-15 09:18:50', NULL, NULL, NULL, '2026-07-16 09:18:50', '2026-07-16 09:18:50', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('15', '20', '2', 'Rancang Bangun Game Edukasi Simulasi Deforestasi : Dampak Penebangan Hutan terhadap Banjir', 'Abstrak untuk Rancang Bangun Game Edukasi Simulasi Deforestasi : Dampak Penebangan Hutan terhadap Banjir', 'Teknik Perangkat Lunak', 'approved', '2026-07-15 09:18:50', NULL, NULL, NULL, '2026-07-16 09:18:50', '2026-07-16 09:18:50', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('16', '6', NULL, 'Perancangan Sistem Crowdsourcing Demand Produk untuk Analisis Kebutuhan Pasar di Indonesia Berbasis Web', 'Abstrak untuk Perancangan Sistem Crowdsourcing Demand Produk untuk Analisis Kebutuhan Pasar di Indonesia Berbasis Web', 'Teknik Perangkat Lunak', 'rejected', '2026-05-29 09:18:50', NULL, NULL, NULL, '2026-07-16 09:18:50', '2026-07-16 09:18:50', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('17', '7', NULL, 'PERANCANGAN SISTEM REKOMENDASI DESTINASI WISATA BERBASIS KEPRIPADIAN & BUDGET PENGGUNA', 'Abstrak untuk PERANCANGAN SISTEM REKOMENDASI DESTINASI WISATA BERBASIS KEPRIPADIAN & BUDGET PENGGUNA', 'Teknik Perangkat Lunak', 'rejected', '2026-05-25 09:18:51', NULL, NULL, NULL, '2026-07-16 09:18:51', '2026-07-16 09:18:51', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('18', '8', NULL, 'RANCANG BANGUN SISTEM E-SURAT DENGAN METODOLOGI AGILE SCRUM DI FAKULTAS KOMPUTER UNIVERSITAS UNIVERSAL (UVERS)', 'Abstrak untuk RANCANG BANGUN SISTEM E-SURAT DENGAN METODOLOGI AGILE SCRUM DI FAKULTAS KOMPUTER UNIVERSITAS UNIVERSAL (UVERS)', 'Teknik Perangkat Lunak', 'rejected', '2026-06-15 09:18:51', NULL, NULL, NULL, '2026-07-16 09:18:51', '2026-07-16 09:18:51', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('19', '8', NULL, 'PERANCANGAN APLIKASI MONITORING, MANAJEMEN, DAN KOLABORASI KEGIATAN HIMPUNAN MAHASISWA UNIVERSITAS UNIVERSAL BERBASIS WEB', 'Abstrak untuk PERANCANGAN APLIKASI MONITORING, MANAJEMEN, DAN KOLABORASI KEGIATAN HIMPUNAN MAHASISWA UNIVERSITAS UNIVERSAL BERBASIS WEB', 'Teknik Perangkat Lunak', 'rejected', '2026-06-07 09:18:51', NULL, NULL, NULL, '2026-07-16 09:18:51', '2026-07-16 09:18:51', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('20', '8', NULL, 'SISTEM REKOMENDASI KARIER BERBASIS DATA AKADEMIK DAN MINAT DENGAN METODE SAW DI UNIVERSITAS UNIVERSAL', 'Abstrak untuk SISTEM REKOMENDASI KARIER BERBASIS DATA AKADEMIK DAN MINAT DENGAN METODE SAW DI UNIVERSITAS UNIVERSAL', 'Teknik Perangkat Lunak', 'rejected', '2026-06-07 09:18:51', NULL, NULL, NULL, '2026-07-16 09:18:51', '2026-07-16 09:18:51', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('21', '9', NULL, 'Gamifikasi Kebersihan Lingkungan : Perancangan Game Simulasi untuk Menumbuhkan Kesadaran Peduli Lingkungan', 'Abstrak untuk Gamifikasi Kebersihan Lingkungan : Perancangan Game Simulasi untuk Menumbuhkan Kesadaran Peduli Lingkungan', 'Teknik Perangkat Lunak', 'rejected', '2026-06-01 09:18:52', NULL, NULL, NULL, '2026-07-16 09:18:52', '2026-07-16 09:18:52', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('22', '10', NULL, 'Rancang Bangun Website Informasi Perawatan Kulit Berjerawat dengan Fitur Rekomendasi Produk dan Edukasi', 'Abstrak untuk Rancang Bangun Website Informasi Perawatan Kulit Berjerawat dengan Fitur Rekomendasi Produk dan Edukasi', 'Teknik Perangkat Lunak', 'rejected', '2026-05-30 09:18:52', NULL, NULL, NULL, '2026-07-16 09:18:52', '2026-07-16 09:18:52', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('23', '11', NULL, 'PERANCANGAN GAME EDUKASI DENGAN PENDEKATAN PROBLEM-BASED LEARNING  UNTUK MATERI GERAK PARABOLA DI SMA', 'Abstrak untuk PERANCANGAN GAME EDUKASI DENGAN PENDEKATAN PROBLEM-BASED LEARNING  UNTUK MATERI GERAK PARABOLA DI SMA', 'Teknik Perangkat Lunak', 'rejected', '2026-06-02 09:18:52', NULL, NULL, NULL, '2026-07-16 09:18:52', '2026-07-16 09:18:52', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('24', '12', NULL, 'Rancang Bangun Game Simulasi Petualangan untuk Mencapai Kebebasan Keuangan Pribadi di Kalangan Generasi-Z', 'Abstrak untuk Rancang Bangun Game Simulasi Petualangan untuk Mencapai Kebebasan Keuangan Pribadi di Kalangan Generasi-Z', 'Teknik Perangkat Lunak', 'rejected', '2026-06-09 09:18:52', NULL, NULL, NULL, '2026-07-16 09:18:52', '2026-07-16 09:18:52', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('25', '13', NULL, 'PERANCANGAN SISTEM MONITORING STOK SPAREPART KOMPUTER BERBASIS WEBSITE PADA CV INNOVATION TECHNOLOGY CENTER', 'Abstrak untuk PERANCANGAN SISTEM MONITORING STOK SPAREPART KOMPUTER BERBASIS WEBSITE PADA CV INNOVATION TECHNOLOGY CENTER', 'Teknik Perangkat Lunak', 'rejected', '2026-05-25 09:18:53', NULL, NULL, NULL, '2026-07-16 09:18:53', '2026-07-16 09:18:53', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('26', '14', NULL, 'PERANCANGANAPLIKASI PEMINJAMAN RUANGAN FASILITAS KAMPUS BERBASIS MOBILE DI UNIVERSITAS UNIVERSAL', 'Abstrak untuk PERANCANGANAPLIKASI PEMINJAMAN RUANGAN FASILITAS KAMPUS BERBASIS MOBILE DI UNIVERSITAS UNIVERSAL', 'Teknik Perangkat Lunak', 'rejected', '2026-06-10 09:18:53', NULL, NULL, NULL, '2026-07-16 09:18:53', '2026-07-16 09:18:53', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('27', '14', NULL, 'PERANCANGAN APLIKASI PENGELOLAAN PRODUK INDUSTRI KREATIF PADA PLUT KUMKM BATAM', 'Abstrak untuk PERANCANGAN APLIKASI PENGELOLAAN PRODUK INDUSTRI KREATIF PADA PLUT KUMKM BATAM', 'Teknik Perangkat Lunak', 'rejected', '2026-06-08 09:18:53', NULL, NULL, NULL, '2026-07-16 09:18:53', '2026-07-16 09:18:53', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('28', '15', NULL, 'RANCANG BANGUN APLIKASI WEB JURNAL HARIAN DENGAN ANALISIS SENTIMEN UNTUK MENDUKUNG KESEHATAN MENTAL MAHASISWA', 'Abstrak untuk RANCANG BANGUN APLIKASI WEB JURNAL HARIAN DENGAN ANALISIS SENTIMEN UNTUK MENDUKUNG KESEHATAN MENTAL MAHASISWA', 'Teknik Perangkat Lunak', 'rejected', '2026-06-01 09:18:53', NULL, NULL, NULL, '2026-07-16 09:18:53', '2026-07-16 09:18:53', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('29', '17', NULL, 'Perancangan dan Implementasi Sistem Informasi Marketplace Penjualan Aksesori Ponsel Berbasis Web Responsif Axxora', 'Abstrak untuk Perancangan dan Implementasi Sistem Informasi Marketplace Penjualan Aksesori Ponsel Berbasis Web Responsif Axxora', 'Teknik Perangkat Lunak', 'rejected', '2026-06-10 09:18:53', NULL, NULL, NULL, '2026-07-16 09:18:53', '2026-07-16 09:18:53', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('30', '18', NULL, 'Pengembangan Aplikasi Gamifikasi Pembelajaran Bahasa Mandarin untuk Meningkatkan Literasi Membaca dan Menulis  bagi Penutur Non-Native', 'Abstrak untuk Pengembangan Aplikasi Gamifikasi Pembelajaran Bahasa Mandarin untuk Meningkatkan Literasi Membaca dan Menulis  bagi Penutur Non-Native', 'Teknik Perangkat Lunak', 'rejected', '2026-06-14 09:18:54', NULL, NULL, NULL, '2026-07-16 09:18:54', '2026-07-16 09:18:54', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('31', '19', NULL, 'PENGEMBANGAN SISTEM PENCATATAN DAN MONITORING DATA PEMINJAMAN SARANA DAN PRASARANA UNIVERSITAS BERBASIS WEB', 'Abstrak untuk PENGEMBANGAN SISTEM PENCATATAN DAN MONITORING DATA PEMINJAMAN SARANA DAN PRASARANA UNIVERSITAS BERBASIS WEB', 'Teknik Perangkat Lunak', 'rejected', '2026-05-19 09:18:54', NULL, NULL, NULL, '2026-07-16 09:18:54', '2026-07-16 09:18:54', NULL, NULL, NULL, '0');
INSERT INTO `thesis_submissions` (`id`, `student_id`, `supervisor_id`, `title`, `abstract`, `research_field`, `status`, `submission_date`, `defense_date`, `notes`, `final_score`, `created_at`, `updated_at`, `deleted_at`, `rubric_id`, `supervisor_2_id`, `is_historical`) VALUES ('32', '20', NULL, 'Rancang Bangun Gameplay Platformer Berbasis 2D dengan Simulasi Visual Dampak Pengelolaan Sampah', 'Abstrak untuk Rancang Bangun Gameplay Platformer Berbasis 2D dengan Simulasi Visual Dampak Pengelolaan Sampah', 'Teknik Perangkat Lunak', 'rejected', '2026-06-13 09:18:54', NULL, NULL, NULL, '2026-07-16 09:18:54', '2026-07-16 09:18:54', NULL, NULL, NULL, '0');

-- Data for comments
TRUNCATE TABLE `comments`;
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('1', '1', '2', NULL, 'Di Latar belakang isinya tidak boleh diambil dari Jurnal semua, perlu dijabarkan permasalahan dari hasil wawancara atau observasi.- Data pendukung: perlu ditambahkan data kuantitatif tentang jumlah sarana prasarana yang dikelola UVERS (misalnya jumlah kelas, proyektor, AC), agar urgensi penelitian lebih terasa.- Rumusan masalah dan tujuan: masih cenderung umum, bisa dibuat lebih spesifik, misalnya “Bagaimana sistem dapat menghasilkan laporan otomatis kondisi fasilitas?” atau “Bagaimana sistem memberikan notifikasi jadwal maintenance?”.- Ruang lingkup sistem: sudah ada batasan fitur, tetapi sebaiknya dijelaskan lebih rinci fitur utama (dashboard monitoring, riwayat maintenance, notifikasi).-Dampak yang diuraikan sudah baik. Untuk memperkuat, proposal bisa menambahkan estimasi kuantitatif, misalnya \"Diharapkan dapat mengurangi waktu pelaporan dari beberapa jam menjadi beberapa menit\" atau \"Meningkatkan akurasi data inventaris aset hingga 99%\".', '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('2', '3', '2', NULL, 'Identifikasi Permasalahan 1. Tidak efisien pada pembuatan dokumen spreadsheet untuk penilaian setiap judul yang diajukan Mahasiswa 2. Sulit dalam melakukan peniliaian 3. Keamanan data karena data dapat diakses oleh user lain. 4. Data tidak terpusat mempersulit dalam memberikan informasi kepada mahasiswa.- Pastikan bahwa penerapan metodologi Agile Scrum dapat menjawab kebutuhan pengembangan yang fleksibel dan iteratif, serta memberikan cukup ruang untuk perubahan sesuai umpan balik dari pemangku kepentingan.- Apakah dampak dari inefisiensi ini cukup signifikan? Dapatkah contoh konkret diberikan, seperti waktu yang terbuang atau masalah dalam pencatatan dan pelacakan data yang pernah terjadi?', '2026-07-16 09:18:47', '2026-07-16 09:18:47', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('3', '5', '2', NULL, 'Harus lebih jelas algoritma yang digunakan untuk dapat merekomendasikan konsumsi gula harian pengguna.- Validasi Sistem: perlu dijelaskan bagaimana sistem grading akan diuji (misalnya, mengacu pada standar WHO atau Kemenkes tentang asupan gula).- Ruang Lingkup: tambahkan batasan agar tidak melebar, misalnya hanya fokus pada minuman kemasan populer di Indonesia. Jelaskan dasar atau acuan untuk algoritma grading-nya (misal: \"diadaptasi dari standar Kemenkes RI atau standar WHO\").', '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('4', '6', '2', NULL, '1. Detailkan Metode Evaluasi: Pada tahap Beta Testing, jelaskan secara spesifik bagaimana efektivitas edukatif akan diukur. Sangat disarankan untuk menggunakan metode pre-test dan post-test kepada siswa untuk mendapatkan data kuantitatif tentang peningkatan pemahaman mereka setelah bermain game.  2. Jelaskan Konsep Game: Untuk memberikan gambaran lebih jelas, bisa ditambahkan satu atau dua kalimat pada bagian Inisiasi  mengenai genre atau konsep inti game (misalnya: puzzle, kuis, petualangan, dll).', '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('5', '7', '2', NULL, 'Rekomendasi harus menggunakan algoritma yang tepat agar sesuai dengan profil pengguna- Ruang Lingkup: masih umum, sebaiknya lebih detail fitur yang akan dikembangkan (misalnya: integrasi GPS, sistem rekomendasi berbasis preferensi, informasi budaya lokal).- Evaluasi Aplikasi: perlu dijelaskan bagaimana efektivitas aplikasi akan diuji (misalnya melalui usability testing, SUS score, atau uji kepuasan pengguna).- Integrasi Budaya Lokal: karena pemandu wisata juga berfungsi sebagai mediator budaya, sebaiknya dijelaskan apakah aplikasi akan mencakup informasi etika, budaya, dan bahasa lokal.- Inovasi Teknis: agar berbeda dari aplikasi peta biasa (Google Maps), perlu ditonjolkan fitur pembeda, misalnya rekomendasi otomatis berbasis machine learning, AR untuk navigasi, atau chatbot interaktif. Sebutkan Teknologi: Cantumkan technology stack yang jelas. Contoh: \"Aplikasi akan dikembangkan secara native untuk Android menggunakan Kotlin, memanfaatkan Google Maps API untuk fitur lokasi, dan Firebase sebagai backend.\". Serta Jelaskan Konsep Rekomendasi: Beri gambaran awal tentang cara kerja sistem rekomendasi (misalnya, berbasis popularitas, berbasis kategori preferensi pengguna, dll).', '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('6', '8', '2', NULL, 'Penulisan rumusan masalah harus mencakup semua yang ada pada identifikasi masalah Pertimbangkan Metodologi Agile: Disarankan untuk mempertimbangkan metode Agile. Mengingat pengguna sistem (admin dan teknisi) dapat memberikan feedback yang berharga selama pengembangan, pendekatan iteratif Agile akan lebih efektif dalam memastikan sistem benar-benar sesuai dengan kebutuhan alur kerja mereka dibandingkan Waterfall.', '2026-07-16 09:18:48', '2026-07-16 09:18:48', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('7', '10', '2', NULL, 'Harus melakukan wawancara atau observasi terhadap stakeholder kemahasiswaan untuk mendapatkan data yang lengkap - Tambahkan Metodenya.- Sebutkan Teknologi: Proposal harus mencantumkan technology stack yang akan dipakai. Contoh: \"Aplikasi akan dibangun dengan Kotlin untuk Android, dan menggunakan Firebase sebagai backend untuk notifikasi real-time.', '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('8', '11', '2', NULL, 'Harus jelas objek penelitian dilakukan dimana- Permasalahan penelitian tidak jelas dan didapat dari mana Secara keseluruhan Isi Proposal harus di pertajam lagi. Mahasiswa harus menetapkan sebuah studi kasus yang nyata, yang masih menggunakan pencatatan manual dan bersedia menjadi objek penelitian. Selanjutnya, menjelaskan secara spesifik bagaimana sistem ini akan memberikan dampak positif bagi perusahaan atau organisasi tersebut. Bagaimana sistem akan dirancang, dibangun, dan diuji. Urgensi harus dikaitkan langsung dengan studi kasus. Setelah studi kasus ditemukan, jelaskan masalah mendesak apa yang sedang mereka hadapi akibat sistem manual (misalnya, sering kehilangan barang, kesulitan audit, dll). Proposal ini harus direvisi secara fundamental dan menyeluruh. Mahasiswa harus melengkapi semua bagian yang hilang, terutama bab metodologi pengembangan perangkat lunak, dan mengaitkan seluruh isi proposal dengan sebuah studi kasus yang konkret.', '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('9', '12', '2', NULL, 'Disarankan untuk fokus pada satu jenjang pendidikan (misalnya, siswa SMP) dan satu mata pelajaran (misalnya, Sejarah atau Biologi). Hal ini akan membuat proyek lebih terarah, dapat dicapai, dan hasil pengujiannya lebih bermakna.', '2026-07-16 09:18:49', '2026-07-16 09:18:49', NULL);
INSERT INTO `comments` (`id`, `thesis_submission_id`, `user_id`, `parent_id`, `content`, `created_at`, `updated_at`, `deleted_at`) VALUES ('10', '15', '2', NULL, 'Spesifikasikan Target Pengujian: Jelaskan target pengguna untuk uji coba (misalnya, siswa SMP atau SMA) agar lebih fokus. Sebutkan Teknologi: Proposal ini belum menyebutkan technology stack. Tambahkan detail teknologi yang akan digunakan (misalnya PHP Laravel, MySQL) untuk melengkapi perencanaan. Hilangkan kontradiksi platform. Pilih satu platform target (Android atau Windows) dan pastikan seluruh dokumen konsisten.', '2026-07-16 09:18:50', '2026-07-16 09:18:50', NULL);

SET FOREIGN_KEY_CHECKS=1;
